general:
  data_path: ../data/
  model_name: jx7789/kobart_summary_v3
  output_dir: ./
inference:
  batch_size: 8
  ckt_path: home/code/
  early_stopping: true
  generate_max_length: 200
  no_repeat_ngram_size: 4
  num_beams: 5
  remove_tokens:
  - <usr>
  - </s>
  - </s>
  - <pad>
  result_path: ./prediction/
tokenizer:
  bos_token: </s>
  decoder_max_len: 200
  encoder_max_len: 1024
  eos_token: </s>
  special_tokens:
  - '#Person1#'
  - '#Person2#'
  - '#Person3#'
  - '#Person4#'
  - '#Person5#'
  - '#Person6#'
  - '#Person7#'
  - '#SSN#'
  - '#PhoneNumber#'
  - '#Address#'
  - '#Email#'
  - '#CarNumber#'
  - '#CardNumber##DateOfBirth#'
  - '#PassportNumber#'
training:
  do_eval: true
  do_train: true
  early_stopping_patience: 3
  early_stopping_threshold: 0.001
  evaluation_strategy: epoch
  fp16: true
  generation_max_length: 200
  gradient_accumulation_steps: 1
  learning_rate: 5.0e-06
  load_best_model_at_end: true
  logging_dir: ./logs
  logging_strategy: epoch
  lr_scheduler_type: cosine_with_restarts
  num_train_epochs: 20
  optim: adamw_torch
  overwrite_output_dir: true
  per_device_eval_batch_size: 8
  per_device_train_batch_size: 8
  predict_with_generate: true
  report_to: wandb
  save_strategy: epoch
  save_total_limit: 7
  seed: 42
  warmup_ratio: 0.1
  weight_decay: 0.01
wandb:
  entity: kkukky-empty
  name: jx7789_kobart_summary_v3-2x75p-5l6-n4-b5
  project: NLP2
